version: 2.1
orbs:
  # Use the CircleCI Android orb version that supports OpenJDK17 required by AGP 8.2+
  android: circleci/android@2.4.0
  codecov: codecov/codecov@3.2.4

jobs:
  build-and-unit-test:
    executor:
      name: android/android-docker
      resource-class: large
      tag: 2024.01.1

    steps:
      - checkout

      - run:
          name: Check format
          command: make checkformat

      - run:
          name: Check style
          command: make checkstyle

      - run:
          name: Javadoc
          command: make javadoc

      - store_artifacts:
          path: code/userprofile/build/docs/javadoc

      - run:
          name: Assemble phone
          command: make assemble-phone

      - run:
          name: Build Jitpack Library
          command: make ci-publish-maven-local-jitpack

      - run:
          name: Build Test app
          command: make assemble-app

      - run:
          name: Run Unit tests
          command: make unit-test-coverage

      - store_test_results:
          path: code/userprofile/build/test-results/testPhoneDebugUnitTest

      - codecov/upload:
          file: code/userprofile/build/reports/coverage/test/phone/debug/report.xml
          flags: unit-tests


  functional-test:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2024.01.1

    steps:      
      - checkout

      - android/create-avd:
          avd-name: myavd
          install: true
          system-image: system-images;android-29;default;x86

      - android/start-emulator:
          avd-name: myavd
          no-window: true
          post-emulator-launch-assemble-command: ""
          restore-gradle-cache-prefix: v1a      

      - run:
          name: Run Functional tests
          command: |
            make functional-test-coverage

      - codecov/upload:
          file: code/core/build/reports/coverage/androidTest/phone/connected/debug/report.xml
          flags: functional-tests

      - android/save-gradle-cache:
          cache-prefix: v1a

workflows:
  build:
    jobs:
      - build-and-unit-test
      - functional-test
